import { test, expect, type APIRequestContext } from "@playwright/test";

/**
 * GP share links (design §15): the public wellness summary at /s/[token],
 * the designed gone state, and the access log that grows on every open.
 *
 * HONESTY (GAP_REVIEW_2 #2): no registered clinician is onboarded, so the GP
 * sees an automated wellness summary with a visible disclaimer — never a
 * fabricated "Dr. S. Nolan, IMC 412887" held out as a real review.
 *
 * Seed fixture: /s/k7f2demo belongs to Aoife Byrne (mem_0001), 1 logged open.
 */

const BEARER = { Authorization: "Bearer demo-member-token" }; // Aoife

async function openedCount(request: APIRequestContext): Promise<number> {
  const res = await request.get("/api/v1/share", { headers: BEARER });
  expect(res.status()).toBe(200);
  const { links } = (await res.json()) as {
    links: { token: string; openedCount: number }[];
  };
  const link = links.find((l) => l.token === "k7f2demo");
  expect(link).toBeTruthy();
  return link!.openedCount;
}

test("/s/k7f2demo renders the honest wellness-summary framing and result rows", async ({
  page,
}) => {
  await page.goto("/s/k7f2demo");
  await expect(page.getByRole("heading", { name: "Aoife Byrne" })).toBeVisible();

  // HONESTY: the disclaimer is visible and no fabricated clinician/IMC appears.
  await expect(
    page.getByText(
      "This is a wellness summary generated by Arcaevo, not a diagnosis or a substitute for clinical assessment."
    )
  ).toBeVisible();
  await expect(page.getByText("not reviewed by a named clinician")).toBeVisible();
  await expect(page.getByText("IMC 412887")).toHaveCount(0);
  await expect(page.getByText("Dr. S. Nolan")).toHaveCount(0);

  // The prev/current/verdict table.
  await expect(page.getByText("Marker", { exact: true })).toBeVisible();
  await expect(page.getByText("Previous", { exact: true })).toBeVisible();
  await expect(page.getByText("Verdict", { exact: true })).toBeVisible();
  // Aoife's seeded recheck story includes verdict rows.
  await expect(
    page.getByText(/^(Improved|No real change|Worsened)$/).first()
  ).toBeVisible();
});

test("unknown token renders the designed gone state (HTTP 200 page)", async ({
  page,
}) => {
  const res = await page.goto("/s/not-a-real-token");
  expect(res?.status()).toBe(200); // the page renders the designed screen
  await expect(
    page.getByRole("heading", { name: "This link is no longer live" })
  ).toBeVisible();
  await expect(page.getByText(/Links expire after 30 days/)).toBeVisible();
});

test("every open of the share API is appended to the access log", async ({
  request,
}) => {
  const before = await openedCount(request);

  // Open twice — the public GET, no auth needed.
  for (let i = 0; i < 2; i += 1) {
    const res = await request.get("/api/v1/share/k7f2demo");
    expect(res.status()).toBe(200);
  }

  const after = await openedCount(request);
  expect(after).toBe(before + 2);
});
